stages:
  - build-image
  - deploy
  
docker_build_development:
  stage: build-image
  tags:
    - kube-ssh
  script:
    - cp /home/config/dev/mindi_nodejs/.env .
    - cp /home/config/dev/mindi_nodejs/Dockerfile .
    - cp /home/config/dev/mindi_nodejs/node-rolling-update.yml .
    - cp -r /home/config/dev/mindi_nodejs/certificates .
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - echo $CI_REGISTRY_IMAGE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - DOCKER_IMG="$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - echo $DOCKER_IMG
    - sed -i "s|gitlab.*|${DOCKER_IMG}|" node-rolling-update.yml
    - kubectl apply -f node-rolling-update.yml
  after_script:
    - curl --request DELETE --data 'name_regex_delete=.*' --data "keep_n=3" --header "$PRIVATE $TOKEN" "http://gitlab.artoon.in/api/v4/projects/4883/registry/repositories/201/tags"
  when: manual
  only:  
    - development 